general {
    lock_cmd = pidof hyprlock || hyprlock -c $HOME/.config/hypr/hyprlock.conf       # comando per bloccare lo schermo
    before_sleep_cmd = loginctl lock-session    # blocca prima di sospendere
    after_sleep_cmd = hyprctl dispatch dpms on  # riaccende il monitor dopo lo sleep
}

listener {
    timeout = 150                                # 2.5 min
    on-timeout = brightnessctl set 10%           # abbassa luminosità
    on-resume = brightnessctl set 100%           # ripristina luminosità
}

listener {
    timeout = 300                                # 5 min
    on-timeout = loginctl lock-session           # blocca sessione
}

listener {
    timeout = 330                                # 5.5 min
    on-timeout = hyprctl dispatch dpms off       # spegne monitor
    on-resume = hyprctl dispatch dpms on         # riaccende monitor
}

listener {
    timeout = 600                                # 10 min
    on-timeout = systemctl suspend               # sospende il PC
}